### ISSUE TITLE
Error at step 6 - cmake not found

### ISSUE THREAD

**Issue by octavianmm** [xuancong84/install-PyTorch-on-Android#1]
Hello,

I'm having an error when finally at step 6 - installing pytorch:

root@localhost:~/pytorch# python3 setup.py install
Building wheel torch-1.4.0a0+7404463
-- Building version 1.4.0a0+7404463
cmake -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/root/pytorch/torch -DCMAKE_PREFIX_PATH=/usr/lib/python3/dist-packages -DPYTHON_EXECUTABLE=/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.8 -DPYTHON_LIBRARY=/usr/lib/libpython3.8.so.1.0 -DTORCH_BUILD_VERSION=1.4.0a0+7404463 -DUSE_NUMPY=True /root/pytorch
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    build_caffe2(version=version,
  File "/root/pytorch/tools/build_pytorch_libs.py", line 54, in build_caffe2
    cmake.generate(version,
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 319, in generate
    self.run(args, env=my_env)
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

However I can see the folder cmake exists....any hints?

Thank you

**Comment by xuancong84** [comment]
The error suggest that you need to install cmake.

Right now, this only works on Python 2 and Python 3.6. In the future, it might work on Python 3.7 and 3.8
